export const TASK_TEMPLATES = {
  "3D": [
    {
      name: "Scale up and take printout",
      estimated_minutes: 120,
      assigned_to: ["dhanush"],
      depends_on: null,
    },
    {
      name: "Armature work",
      estimated_minutes: 600,
      assigned_to: ["dhanush", "john"],
      depends_on: 1,
    },
    {
      name: "Jute layer",
      estimated_minutes: 240,
      assigned_to: ["john"],
      depends_on: 2,
    },
    {
      name: "Prepare clay",
      estimated_minutes: 720,
      assigned_to: ["john"],
      depends_on: 3,
    },
    {
      name: "Basic layer of clay",
      estimated_minutes: 240,
      assigned_to: ["dhanush", "john"],
      depends_on: 4,
    },
    {
      name: "Detailing",
      estimated_minutes: 1200,
      assigned_to: ["dhanush"],
      depends_on: 5,
    },
    {
      name: "Client approval",
      estimated_minutes: 1440,
      assigned_to: ["client"],
      depends_on: 6,
    },
    {
      name: "Mould ready clay work",
      estimated_minutes: 480,
      assigned_to: ["dhanush"],
      depends_on: 7,
    },
    {
      name: "Moulding",
      estimated_minutes: 300,
      assigned_to: ["external"],
      depends_on: 8,
    },
    {
      name: "Casting in FRP",
      estimated_minutes: 1440,
      assigned_to: ["external"],
      depends_on: 9,
    },
    {
      name: "Finishing FRP",
      estimated_minutes: 1440,
      assigned_to: ["dhanush", "john"],
      depends_on: 10,
    },
    {
      name: "Painting and lacquering",
      estimated_minutes: 1440,
      assigned_to: ["external"],
      depends_on: 11,
    },
    {
      name: "Brass casting",
      estimated_minutes: 20160,
      assigned_to: ["external"],
      depends_on: 12,
    },
    {
      name: "First level finishing",
      estimated_minutes: 600,
      assigned_to: ["john"],
      depends_on: 13,
    },
    {
      name: "Attaching brass pieces",
      estimated_minutes: 1440,
      assigned_to: ["dhanush", "john"],
      depends_on: 14,
    },
    {
      name: "Brass wielding",
      estimated_minutes: 960,
      assigned_to: ["external"],
      depends_on: 15,
    },
    {
      name: "Grinding wielded portion",
      estimated_minutes: 480,
      assigned_to: ["john"],
      depends_on: 16,
    },
    {
      name: "Sandblasting",
      estimated_minutes: 720,
      assigned_to: ["john"],
      depends_on: 17,
    },
    {
      name: "Finishing touches/rewielding",
      estimated_minutes: 720,
      assigned_to: ["dhanush"],
      depends_on: 18,
    },
    {
      name: "Patina work",
      estimated_minutes: 360,
      assigned_to: ["dhanush"],
      depends_on: 19,
    },
    {
      name: "Sealing patina",
      estimated_minutes: 60,
      assigned_to: ["dhanush"],
      depends_on: 20,
    },
  ],

  "2D": [
    {
      name: "Scale up and take printout",
      estimated_minutes: 120,
      assigned_to: ["dhanush"],
      depends_on: null,
    },
    {
      name: "Ready clay slab",
      estimated_minutes: 360,
      assigned_to: ["john"],
      depends_on: 1,
    },
    {
      name: "Apply clay slab",
      estimated_minutes: 180,
      assigned_to: ["john"],
      depends_on: 2,
    },
    {
      name: "Draw image on clay",
      estimated_minutes: 120,
      assigned_to: ["dhanush"],
      depends_on: 3,
    },
    {
      name: "Emboss on clay slab",
      estimated_minutes: 1440,
      assigned_to: ["dhanush", "john"],
      depends_on: 4,
    },
    {
      name: "Detailing",
      estimated_minutes: 1440,
      assigned_to: ["dhanush"],
      depends_on: 5,
    },
    {
      name: "Client approval",
      estimated_minutes: 1440,
      assigned_to: ["client"],
      depends_on: 6,
    },
    {
      name: "Mould ready clay work",
      estimated_minutes: 300,
      assigned_to: ["dhanush"],
      depends_on: 7,
    },
    {
      name: "Moulding",
      estimated_minutes: 300,
      assigned_to: ["external"],
      depends_on: 8,
    },
    {
      name: "Casting in FRP",
      estimated_minutes: 1440,
      assigned_to: ["external"],
      depends_on: 9,
    },
    {
      name: "Finishing FRP",
      estimated_minutes: 1440,
      assigned_to: ["dhanush", "john"],
      depends_on: 10,
    },
    {
      name: "Painting and lacquering",
      estimated_minutes: 1440,
      assigned_to: ["external"],
      depends_on: 11,
    },
    {
      name: "Brass casting",
      estimated_minutes: 10080,
      assigned_to: ["external"],
      depends_on: 12,
    },
    {
      name: "Brass wielding",
      estimated_minutes: 480,
      assigned_to: ["dhanush"],
      depends_on: 13,
    },
    {
      name: "Grinding wielded portion",
      estimated_minutes: 360,
      assigned_to: ["john"],
      depends_on: 14,
    },
    {
      name: "Sandblasting",
      estimated_minutes: 240,
      assigned_to: ["john"],
      depends_on: 15,
    },
    {
      name: "Finishing touches/rewielding",
      estimated_minutes: 120,
      assigned_to: ["dhanush"],
      depends_on: 16,
    },
    {
      name: "Patina work",
      estimated_minutes: 180,
      assigned_to: ["dhanush"],
      depends_on: 17,
    },
    {
      name: "Sealing patina",
      estimated_minutes: 720,
      assigned_to: ["dhanush"],
      depends_on: 18,
    },
  ],

  OTHERS: [
    {
      name: "Scale up and take printout",
      estimated_minutes: 120,
      assigned_to: ["dhanush"],
      depends_on: null,
    },
    {
      name: "Armature work",
      estimated_minutes: 360,
      assigned_to: ["dhanush", "john"],
      depends_on: 1,
    },
    {
      name: "Jute layer",
      estimated_minutes: 240,
      assigned_to: ["john"],
      depends_on: 2,
    },
    {
      name: "Prepare clay",
      estimated_minutes: 360,
      assigned_to: ["john"],
      depends_on: 3,
    },
    {
      name: "Basic layer of clay",
      estimated_minutes: 480,
      assigned_to: ["dhanush", "john"],
      depends_on: 4,
    },
    {
      name: "Detailing",
      estimated_minutes: 960,
      assigned_to: ["dhanush"],
      depends_on: 5,
    },
    {
      name: "Client approval",
      estimated_minutes: 1440,
      assigned_to: ["client"],
      depends_on: 6,
    },
  ],
} as const;
