export const TASK_TEMPLATES = {
  '3D': [
    { title: 'Scale up and take printout', estimated_minutes: 120, assigned_to: 'dhanush', order: 1 },
    { title: 'Armature work', estimated_minutes: 600, assigned_to: 'dhanush', order: 2, dependencies: [1] },
    { title: 'Jute layer', estimated_minutes: 240, assigned_to: 'john', order: 3, dependencies: [2] },
    { title: 'Prepare clay', estimated_minutes: 720, assigned_to: 'john', order: 4, dependencies: [3] },
    { title: 'Basic layer of clay', estimated_minutes: 240, assigned_to: 'dhanush', order: 5, dependencies: [4] },
    { title: 'Detailing', estimated_minutes: 1200, assigned_to: 'dhanush', order: 6, dependencies: [5] },
    { title: 'Client approval', estimated_minutes: 1440, assigned_to: 'client', order: 7, dependencies: [6] },
    { title: 'Mould ready clay work', estimated_minutes: 480, assigned_to: 'dhanush', order: 8, dependencies: [7] },
    { title: 'Moulding', estimated_minutes: 300, assigned_to: 'external', order: 9, dependencies: [8] },
    { title: 'Casting in FRP', estimated_minutes: 1440, assigned_to: 'external', order: 10, dependencies: [9] },
    { title: 'Finishing FRP', estimated_minutes: 1440, assigned_to: 'dhanush', order: 11, dependencies: [10] },
    { title: 'Painting and lacquering', estimated_minutes: 1440, assigned_to: 'external', order: 12, dependencies: [11] },
    { title: 'Brass casting', estimated_minutes: 20160, assigned_to: 'external', order: 13, dependencies: [12] },
    { title: 'First level finishing', estimated_minutes: 600, assigned_to: 'john', order: 14, dependencies: [13] },
    { title: 'Attaching brass pieces', estimated_minutes: 1440, assigned_to: 'dhanush', order: 15, dependencies: [14] },
    { title: 'Brass wielding', estimated_minutes: 960, assigned_to: 'external', order: 16, dependencies: [15], waiting_minutes: 120 },
    { title: 'Grinding wielded portion', estimated_minutes: 480, assigned_to: 'john', order: 17, dependencies: [16] },
    { title: 'Sandblasting', estimated_minutes: 720, assigned_to: 'john', order: 18, dependencies: [17] },
    { title: 'Finishing touches/rewielding', estimated_minutes: 720, assigned_to: 'dhanush', order: 19, dependencies: [18] },
    { title: 'Patina work', estimated_minutes: 360, assigned_to: 'dhanush', order: 20, dependencies: [19], waiting_minutes: 120 },
    { title: 'Sealing patina', estimated_minutes: 60, assigned_to: 'dhanush', order: 21, dependencies: [20], waiting_minutes: 120 },
  ],
  
  '2D': [
    { title: 'Scale up and take printout', estimated_minutes: 120, assigned_to: 'dhanush', order: 1 },
    { title: 'Ready clay slab', estimated_minutes: 360, assigned_to: 'john', order: 2, dependencies: [1], waiting_minutes: 720 },
    { title: 'Apply clay slab', estimated_minutes: 180, assigned_to: 'john', order: 3, dependencies: [2] },
    { title: 'Draw image on clay', estimated_minutes: 120, assigned_to: 'dhanush', order: 4, dependencies: [3] },
    { title: 'Emboss on clay slab', estimated_minutes: 1440, assigned_to: 'dhanush', order: 5, dependencies: [4] },
    { title: 'Detailing', estimated_minutes: 1440, assigned_to: 'dhanush', order: 6, dependencies: [5] },
    { title: 'Client approval', estimated_minutes: 1440, assigned_to: 'client', order: 7, dependencies: [6] },
    { title: 'Mould ready clay work', estimated_minutes: 300, assigned_to: 'dhanush', order: 8, dependencies: [7] },
    { title: 'Moulding', estimated_minutes: 300, assigned_to: 'external', order: 9, dependencies: [8], waiting_minutes: 960 },
    { title: 'Casting in FRP', estimated_minutes: 1440, assigned_to: 'external', order: 10, dependencies: [9], waiting_minutes: 720 },
    { title: 'Finishing FRP', estimated_minutes: 1440, assigned_to: 'dhanush', order: 11, dependencies: [10] },
    { title: 'Painting and lacquering', estimated_minutes: 1440, assigned_to: 'external', order: 12, dependencies: [11], waiting_minutes: 960 },
    { title: 'Brass casting', estimated_minutes: 10080, assigned_to: 'external', order: 13, dependencies: [12], waiting_minutes: 960 },
    { title: 'Brass wielding', estimated_minutes: 480, assigned_to: 'dhanush', order: 14, dependencies: [13], waiting_minutes: 120 },
    { title: 'Grinding wielded portion', estimated_minutes: 360, assigned_to: 'john', order: 15, dependencies: [14] },
    { title: 'Sandblasting', estimated_minutes: 240, assigned_to: 'john', order: 16, dependencies: [15] },
    { title: 'Finishing touches/rewielding', estimated_minutes: 120, assigned_to: 'dhanush', order: 17, dependencies: [16] },
    { title: 'Patina work', estimated_minutes: 180, assigned_to: 'dhanush', order: 18, dependencies: [17], waiting_minutes: 60 },
    { title: 'Sealing patina', estimated_minutes: 720, assigned_to: 'dhanush', order: 19, dependencies: [18], waiting_minutes: 120 },
  ],
  
  'OTHERS': [
    { title: 'Scale up and take printout', estimated_minutes: 120, assigned_to: 'dhanush', order: 1 },
    { title: 'Armature work', estimated_minutes: 360, assigned_to: 'dhanush', order: 2, dependencies: [1] },
    { title: 'Jute layer', estimated_minutes: 240, assigned_to: 'john', order: 3, dependencies: [2] },
    { title: 'Prepare clay', estimated_minutes: 360, assigned_to: 'john', order: 4, dependencies: [3] },
    { title: 'Basic layer of clay', estimated_minutes: 480, assigned_to: 'dhanush', order: 5, dependencies: [4] },
    { title: 'Detailing', estimated_minutes: 960, assigned_to: 'dhanush', order: 6, dependencies: [5] },
    { title: 'Client approval', estimated_minutes: 1440, assigned_to: 'client', order: 7, dependencies: [6] },
  ],
}
